name: ğŸš€ Deploy Application
run-name: ğŸš€ Deploy App | Branch:${{ github.ref_name }} | By @${{ github.actor }}

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**' # Only runs when application code or manifests change

jobs:
  deploy-app:
    name: "ğŸš€ Deploy Application"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: commit-cluster-producer
          location: me-west1-a
          project_id: commit-gcp-psc-eran-meir

      - name: ğŸš€ Apply Kubernetes Manifests
        run: |
          echo "Deploying the app from app/k8s/..."
          kubectl apply -f app/k8s/nginx.yaml
          
      - name: â³ Wait for Rollout
        run: |
          kubectl rollout status deployment/nginx