name: ğŸš€ Deploy Application
run-name: ğŸš€ Deploy App | Branch:${{ github.ref_name }} | By @${{ github.actor }}

on:
  workflow_dispatch:

# Guarantees GKE cluster is only ever processing the absolute latest version of the code, eliminating the race condition.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-app:
    name: "ğŸš€ Deploy Application"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: commit-cluster-producer
          location: me-west1-a
          project_id: commit-gcp-psc-eran-meir

      - name: ğŸ” Generate Internal SSL Certificate
        run: |
          echo "Generating self-signed cert for Nginx..."
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=commit-demo.internal"
          
          echo "Creating Kubernetes Secret..."
          kubectl create secret tls nginx-tls-secret --key tls.key --cert tls.crt --dry-run=client -o yaml | kubectl apply -f -

      - name: ğŸš€ Apply Kubernetes Manifests
        run: |
          echo "Deploying the app from app/k8s/..."
          # The trailing slash tells it to apply ALL yaml files in the folder
          kubectl apply -f app/k8s/ 

      - name: â³ Wait for Rollout
        run: |
          echo "Waiting for Flask App to be ready..."
          kubectl rollout status deployment/flask-app
          
          echo "Waiting for Nginx Ingress to be ready..."
          kubectl rollout status deployment/nginx-ingress